"""Initial-conditions density loader: MP-GenIC ``bigfile`` particles -> mesh.

Streams particle ``Position`` from the IC bigfile in chunks and paints them onto
a periodic ``nmesh^3`` mesh (cloud-in-cell, :mod:`priya_loader.mesh`), returning
the overdensity ``delta = rho/<rho> - 1``. The full particle load is never
resident: peak memory is ``~2 * nmesh^3`` float64 plus one chunk (see
:mod:`priya_loader.mesh`), so coarse meshes run on a NERSC login node
(recommended ``nmesh <= 512``). ``bigfile`` is an optional dependency
(``pip install priya_loader[ic]``).

What this field IS
------------------
* Two fields are available:
    - ``field="cic"`` (default): the **Eulerian density of the displaced
      particles** — CIC-paint of the LPT/Zel'dovich ``Position`` block.
    - ``field="icdensity"``: the **native linear density contrast delta_1** on the
      **Lagrangian** grid (the ``ICDensity`` block reshaped by ``ID``). This is the
      linear field a field-level bias estimator (de Belsunce et al.) wants. It is
      Lagrangian-indexed delta_1(q), which equals the Eulerian linear field at
      first order (valid for linear bias; the z=99 displacements are tiny).
      Caveats: it carries GenIC's ~1-cell Gaussian k-smoothing (sub-percent at
      k<~1 h/Mpc); it is window-free only at ``nmesh == ngrid`` — for
      ``nmesh < ngrid`` the block-average imposes a real-space top-hat (a *sinc*
      window, NOT the CIC ``sinc^2``) that does not cancel in b_F, so deconvolve
      for finite-k (it -> 1 at the low-k modes that drive the leading bias). gas
      vs dm here selects the species' own CLASS transfer (gas=baryon, dm=CDM).
      Prefer ``"icdensity"`` for the bias cross-spectrum; ``"cic"`` for the
      Eulerian/evolved density.
* **At the IC redshift** ``z_init ~ 99`` — the returned amplitude is the z=99
  one. For a bias cross-spectrum at the flux redshift, the consumer must rescale
  by the linear growth factor ``D(z_flux) / D(z_init)`` (a scale-independent
  scalar; e.g. ~26x at z=2.8). We expose ``Omega0/OmegaLambda/Time`` in ``meta``
  so ``D(z)`` is computable; the rescale itself is left to the consumer.
  (At z=99 the displacements are tiny, so this field ~ the linear field.)
* **Real space** (``space="real"``; cf. ``TauGrid.space == "redshift"``).
  Crossing this real-space delta with the redshift-space flux is the *intended*
  Kaiser estimator (gives the full mu-shape for b_F and beta_F) — do not add RSD.
* **Raw, uncompensated CIC** (``field="cic"`` only) — carries the CIC ``sinc^2``
  window; deconvolve for an unbiased finite-k cross-spectrum (see
  :mod:`priya_loader.mesh`). (The ``"icdensity"`` route's window is a *sinc*
  top-hat, not ``sinc^2`` — see above.)
* **``ptype="dm"`` is a total-matter proxy** — exact at ``k -> 0``; baryons
  differ at the percent level on quasilinear scales at z=99.

Co-registration with a tau cube (read this before cross-correlating)
--------------------------------------------------------------------
``ICField.delta`` is indexed ``[x, y, z]`` (``axes = ("x", "y", "z")``), origin 0,
cell ``box/nmesh`` — the same grid origin as the fake_spectra ``cofm``. The tau
cube from :func:`priya_loader.load_tau_grid` is **anisotropic**:
``(ngrid, ngrid, nbins)`` with ``nbins != ngrid``, its first two axes transverse
(``box/ngrid``) and its **last axis a redshift-space velocity axis**
(``dv_kms ~ 10`` km/s), ordered per ``TauGrid.cube_axes`` (e.g. axis=1 -> y,z,x).
So:
  * match the **transverse** plane by painting at ``nmesh = tau.ngrid`` (=480)
    and transposing the IC mesh to ``cube_axes``;
  * the **LOS** axis is NOT a common ``nmesh`` — resample tau's velocity LOS onto
    a common comoving grid (using ``tau.meta["dv_kms"]`` / ``units.velfac``), or
    use a transverse/projected cross-statistic.
The loader only meshes the IC; it never transforms tau.

Provenance (see PROVENANCE.md)
-----------------------------
* ``Position`` = Lagrangian grid ``q`` + 1LPT Zel'dovich displacement ``Psi``
  (``libgenic/zeldovich.c:243-244`` ``Pos += Disp``; written ``save.c:73``;
  MP-Gadget @ 471711f8). First order only — no 2LPT.
* The native ``ICDensity`` block (read by ``field="icdensity"``) is the **linear
  density contrast delta_1** on the Lagrangian grid (= white noise x ``DeltaSpec(k)``,
  ``zeldovich.c:182,284`` / ``power.c:52-65``; saved ``save.c:72``), with a
  ~1-cell Gaussian smoothing. That is the exact ``delta_1`` a field-level bias
  estimator wants; the CIC-of-``Position`` field here equals it to O(delta^2) at
  z=99 but carries the CIC window. The native linear field is available via
  ``field="icdensity"`` (exact at ``nmesh==ngrid``; a sinc top-hat below that).
* The IC linear power spectrum / transfer functions are generated by **CLASS**
  (the ``classy`` Python binding; older sims used ``classylss``), NOT CAMB, in
  ``SimulationRunner/simulationics.py::cambfile()`` (@ 5adf4fe); the
  ``camb_linear/`` dir name and ``camb_git`` field are legacy CAMB labels
  (``camb_git`` = the binding version, ``classy.__version__``).

Units: ``Position`` is comoving kpc/h; ``box`` is reported in Mpc/h.
"""
from __future__ import annotations

import os
import warnings
from dataclasses import dataclass
from dataclasses import field as dc_field
from typing import Any, Dict, Union

import numpy as np

from . import mesh, units

StrPath = Union[str, os.PathLike]

#: particle-type name -> bigfile block prefix (MP-Gadget convention: 0 gas, 1 DM)
PTYPE = {"gas": 0, "dm": 1}


@dataclass
class ICField:
    """Initial-condition overdensity on a mesh."""

    delta: np.ndarray            # (nmesh, nmesh, nmesh) float32 overdensity
    nmesh: int
    box: float                   # Mpc/h
    ptype: str                   # "gas" | "dm"
    redshift: float              # IC redshift (z_init, ~99); see growth note below
    npart: int                   # particles painted
    axes: tuple = ("x", "y", "z")
    space: str = "real"          # real space (cf. TauGrid.space == "redshift")
    meta: Dict[str, Any] = dc_field(default_factory=dict, repr=False)


@dataclass
class ICVelocityField:
    """IC velocity (or momentum) field on a mesh, in peculiar km/s.

    Note: the public attributes ``.field`` and ``.units`` intentionally shadow
    the module-level names ``dataclasses.field`` and ``priya_loader.units``
    inside this class body (they are already documented/used by that name in
    the notebook and README, so we don't rename them). That's why the ``field``
    import above is aliased to ``dc_field`` for the ``meta`` default below:
    unaliased, giving ``field`` a default value here (rather than leaving it
    annotation-only) would silently rebind the class-body name ``field`` to a
    plain string, and ``field(default_factory=dict, ...)`` would then try to
    call a ``str`` and raise a confusing ``TypeError``.
    """

    v: np.ndarray                # (3, nmesh, nmesh, nmesh) float32
    nmesh: int
    box: float                   # Mpc/h
    ptype: str                   # "gas" | "dm"
    redshift: float              # IC redshift (z_init, ~99)
    field: str                   # "velocity" (p/n) | "momentum" (p)
    npart: int
    units: str = "km/s (peculiar)"
    axes: tuple = ("x", "y", "z")
    space: str = "real"
    meta: Dict[str, Any] = dc_field(default_factory=dict, repr=False)


def load_ic_particles(
    ic_dir: StrPath,
    ptype: str = "dm",
    columns=("Position",),
    subsample: int = 1,
    chunk_size: int = 8_000_000,
    velocity: str = "peculiar_kms",
):
    """Load **raw** IC particle columns — NO meshing — so you can paint with your
    own CIC (nbodykit / Pylians) or use the positions directly.

    Use this if you want full control of the mass assignment rather than the
    built-in CIC. (For the linear ``delta_1`` itself you don't need any CIC: use
    ``load_ic_density(..., field="icdensity")``, which only reshapes the
    ``ICDensity`` block.)

    Parameters
    ----------
    ic_dir, ptype : as :func:`load_ic_density`.
    columns : tuple of {"Position", "Velocity", "ICDensity", "ID"}
        Blocks to read. ``Position`` is comoving kpc/h. ``Velocity`` is peculiar
        km/s by default (see ``velocity``).
    subsample : int
        Keep every ``subsample``-th particle (strided, memory-aware). For a full
        1536^3/3072^3 load prefer a compute node or ``nbodykit.BigFileCatalog``.
    velocity : {"peculiar_kms", "raw"}
        How to return the ``Velocity`` column (ignored if ``"Velocity"`` is not
        in ``columns``). ``"peculiar_kms"`` (default) converts the stored block
        to physical peculiar km/s by dispatching on the IC Header's
        ``UsePeculiarVelocity`` flag (see :func:`priya_loader.units.
        ic_velocity_to_peculiar_kms`); PRIYA sets this flag to 1, so PRIYA
        velocities are guaranteed to come back unchanged. ``"raw"`` returns the
        stored block unmodified, whatever its convention. If the flag is absent
        from the Header, ``"peculiar_kms"`` raises rather than guessing.

    Returns
    -------
    (data, header) : (dict[str, np.ndarray], dict)
        ``data[col]`` arrays; ``header`` has ``box_mpc_h``, ``box_kpc_h``,
        ``hubble``, ``redshift``, ``scale_factor``, ``use_peculiar_velocity``,
        ``velocity_units``, ``Omega0``, ``OmegaLambda`` (``None`` if the IC
        Header lacks either attr). ``velocity_units`` is ``"km/s (peculiar)"``
        when ``"Velocity"`` was requested and converted, ``"raw (as stored)"``
        when ``"Velocity"`` was requested with ``velocity="raw"``, and ``None``
        whenever no ``Velocity`` was actually loaded and converted — including
        when ``"Velocity"`` was not in ``columns`` at all, so as to never assert
        a convention for data that was not returned.
    """
    if ptype not in PTYPE:
        raise ValueError(f"ptype must be one of {sorted(PTYPE)}; got {ptype!r}")
    if subsample < 1:
        raise ValueError(f"subsample must be >= 1; got {subsample}")
    if velocity not in ("peculiar_kms", "raw"):
        raise ValueError(f"velocity must be 'peculiar_kms' or 'raw'; got {velocity!r}")
    try:
        import bigfile
    except ImportError as e:  # pragma: no cover
        raise ImportError("reading ICs needs bigfile: pip install priya_loader[ic]") from e

    t = PTYPE[ptype]
    try:
        bf = bigfile.File(str(ic_dir))
    except Exception as e:
        raise ValueError(f"{ic_dir}: cannot open IC bigfile ({e!r})") from e
    data = {}
    with bf:
        try:
            attrs = bf["Header"].attrs
            keys = set(attrs.keys())
        except Exception as e:
            raise ValueError(f"{ic_dir}: cannot read IC Header ({e!r}); skeleton/corrupt?") from e
        box_kpc_h = _attr(attrs, "BoxSize") if "BoxSize" in keys else float("nan")
        time = _attr(attrs, "Time") if "Time" in keys else None
        if "Redshift" in keys:
            redshift = _attr(attrs, "Redshift")
        elif time is not None:
            redshift = units.scale_factor_to_redshift(time)
        else:
            redshift = float("nan")
        if time is None and np.isfinite(redshift):
            time = units.redshift_to_scale_factor(redshift)
        upv = int(_attr(attrs, "UsePeculiarVelocity")) if "UsePeculiarVelocity" in keys else None
        omega0 = _attr(attrs, "Omega0") if "Omega0" in keys else None
        omega_lambda = _attr(attrs, "OmegaLambda") if "OmegaLambda" in keys else None
        header = {
            "box_kpc_h": box_kpc_h,
            "box_mpc_h": units.kpc_h_to_mpc_h(box_kpc_h),
            "hubble": _attr(attrs, "HubbleParam") if "HubbleParam" in keys else None,
            "redshift": redshift,
            "scale_factor": time,
            "use_peculiar_velocity": upv,
            "velocity_units": None,       # filled in below, once we know what was loaded
            "Omega0": omega0,
            "OmegaLambda": omega_lambda,
        }
        for col in columns:
            name = f"{t}/{col}"
            if name not in bf.blocks:
                raise ValueError(f"{ic_dir}: no '{name}' block (ptype={ptype!r}, column={col!r})")
            blk = bf[name]
            n = int(blk.size)
            if subsample == 1:
                data[col] = blk[:]
            else:
                parts = []
                for s in range(0, n, chunk_size):
                    end = min(s + chunk_size, n)
                    start = (-s) % subsample            # keep global indices == 0 mod subsample
                    # .copy() is load-bearing, not defensive: a strided slice is a VIEW that
                    # keeps its whole (chunk_size-row) parent alive. Holding those views in
                    # `parts` would pin every chunk ever read -- i.e. the entire block -- so
                    # `subsample` would bound the OUTPUT but not the MEMORY (87 GB of Position
                    # at 1536^3). Copying releases each chunk at the end of its iteration.
                    parts.append(blk[s:end][start::subsample].copy())
                data[col] = np.concatenate(parts) if parts else blk[0:0]
        if "Velocity" in data:
            if velocity == "peculiar_kms":
                # Raises if upv is None (never guess); header keeps velocity_units=None
                # on that path since we never reach the assignment below.
                data["Velocity"] = units.ic_velocity_to_peculiar_kms(
                    data["Velocity"], time, upv,
                ).astype("f4", copy=False)
                header["velocity_units"] = "km/s (peculiar)"
            else:                                       # velocity == "raw"
                header["velocity_units"] = "raw (as stored)"
        # else: "Velocity" was not requested -> velocity_units stays None (nothing to label).
    return data, header


def _icbrt(n: int) -> int:
    """Exact integer cube root of ``n``, or raise (n is not a perfect cube)."""
    g = int(round(n ** (1.0 / 3.0)))
    for c in (g - 1, g, g + 1):
        if c > 0 and c ** 3 == n:
            return c
    raise ValueError(f"ICDensity route: {n} particles is not a perfect cube (ngrid^3)")


def _load_icdensity_grid(bf, t, nmesh, chunk_size):
    """Return (delta_1, npart): the native linear ``ICDensity`` field on the
    Lagrangian grid, block-averaged to ``nmesh^3``, plus the particle count.

    ``ICDensity`` is the linear density contrast at each particle's Lagrangian
    grid site. The row-major site is ``(ID - 1) mod ngrid^3`` (the per-type
    ``FirstID`` is a multiple of ``ngrid^3``), so no ID sort/min pass is needed.
    Streamed in chunks (memory-safe): resident RAM is ~3*nmesh^3 float64
    (``ssum`` + ``cnt`` + one transient bincount) + one chunk.

    Exact only at ``nmesh == ngrid``; for ``nmesh < ngrid`` the block-average is
    a real-space top-hat (a ``sinc`` window on delta_1(k)) — fine at low k,
    deconvolve for finite-k cross-spectra. ``nmesh`` should divide ``ngrid``.
    """
    idblk = bf[f"{t}/ID"]
    dblk = bf[f"{t}/ICDensity"]
    npart = int(idblk.size)
    if npart == 0:
        raise ValueError("ICDensity route: empty ID block")
    if int(dblk.size) != npart:
        raise ValueError(f"ICDensity route: ID ({npart}) and ICDensity ({dblk.size}) sizes differ")
    ngrid = _icbrt(npart)
    if nmesh > ngrid:
        raise ValueError(
            f"ICDensity route: nmesh={nmesh} > ngrid={ngrid} (cannot upsample a block-average)"
        )
    if ngrid % nmesh != 0:
        warnings.warn(
            f"ICDensity downsample is uneven: nmesh={nmesh} does not divide ngrid={ngrid}"
        )

    n3 = nmesh * nmesh * nmesh
    ssum = np.zeros(n3, dtype=np.float64)
    cnt = np.zeros(n3, dtype=np.float64)
    ng2 = ngrid * ngrid
    gmin = gmax = None
    for s in range(0, npart, chunk_size):
        stop = min(s + chunk_size, npart)
        ids = idblk[s:stop].astype(np.int64)
        lo, hi = int(ids.min()), int(ids.max())
        gmin = lo if gmin is None else min(gmin, lo)
        gmax = hi if gmax is None else max(gmax, hi)
        lag = (ids - 1) % npart                              # within-type row-major index
        i = (lag // ng2) * nmesh // ngrid
        j = ((lag // ngrid) % ngrid) * nmesh // ngrid
        k = (lag % ngrid) * nmesh // ngrid
        flat = (i * nmesh + j) * nmesh + k
        ssum += np.bincount(flat, weights=dblk[s:stop].astype(np.float64), minlength=n3)
        cnt += np.bincount(flat, minlength=n3)
    # Completeness: a full type block has contiguous IDs, so range == count.
    if gmax - gmin + 1 != npart:
        raise ValueError(
            f"ICDensity route: IDs are not a complete contiguous block "
            f"(range {gmax - gmin + 1} != count {npart}); partial/corrupt IC?"
        )
    # Alignment: MP-Gadget FirstID is a multiple of ngrid^3 (id = ...+1+FirstID),
    # so (min(id) - 1) must be 0 mod npart for (id-1)%npart to be the grid index.
    if (gmin - 1) % npart != 0:
        raise ValueError(
            f"ICDensity route: ID block start {gmin} is not ngrid^3-aligned "
            f"(non-standard FirstID); cannot map to the Lagrangian grid"
        )
    cnt[cnt == 0] = 1.0
    return (ssum / cnt).reshape(nmesh, nmesh, nmesh).astype(np.float32), npart


def _attr(attrs, key):
    """Read a scalar bigfile Header attr as a python float.

    bigfile stores attrs as arrays, so scalars come back as 1-element arrays.
    Only call this on scalar attrs — ``ravel()[0]`` would silently take the first
    element of a vector attr (e.g. ``MassTable``).
    """
    return float(np.asarray(attrs[key]).ravel()[0])


def load_ic_density(
    ic_dir: StrPath,
    ptype: str = "dm",
    nmesh: int = 256,
    chunk_size: int = 8_000_000,
    backend: str = "numpy",
    field: str = "cic",
) -> ICField:
    """Load the IC density field for one particle type as an ``nmesh^3`` overdensity.

    Parameters
    ----------
    ic_dir : str or os.PathLike
        An MP-GenIC IC bigfile directory (contains ``Header`` and ``<t>/Position``).
    ptype : {"dm", "gas"}
        Particle type (1=DM, 0=gas).
    nmesh : int
        Mesh cells per side (coarse default; raise for finer fields).
    chunk_size : int
        Particles read per streaming chunk (memory vs. overhead tradeoff).
    backend : {"numpy"}
        Painter backend. Only the lightweight numpy CIC is implemented; an
        ``nbodykit`` backend may be added later.
    field : {"cic", "icdensity"}
        ``"cic"`` (default): CIC overdensity of the displaced ``Position`` block.
        ``"icdensity"``: the native linear ``delta_1`` (``ICDensity`` block
        reshaped by ``ID`` to the Lagrangian grid, block-averaged to ``nmesh``) —
        the exact linear field for the bias cross-spectrum.

    Returns
    -------
    ICField
        For ``field="icdensity"`` ``delta`` is the Lagrangian linear ``delta_1``
        (not mean-subtracted; ``nmesh`` should divide ``ngrid``, ``nmesh<=ngrid``);
        for ``"cic"`` it is the Eulerian overdensity ``rho/<rho>-1``.
    """
    if ptype not in PTYPE:
        raise ValueError(f"ptype must be one of {sorted(PTYPE)}; got {ptype!r}")
    if backend != "numpy":
        raise ValueError(f"unknown backend {backend!r} (only 'numpy' is implemented)")
    if field not in ("cic", "icdensity"):
        raise ValueError(f"field must be 'cic' or 'icdensity'; got {field!r}")
    if nmesh < 1 or chunk_size < 1:
        raise ValueError(f"nmesh and chunk_size must be >= 1 (got {nmesh}, {chunk_size})")
    try:
        import bigfile
    except ImportError as e:  # pragma: no cover
        raise ImportError("reading ICs needs bigfile: pip install priya_loader[ic]") from e

    t = PTYPE[ptype]
    try:
        bf = bigfile.File(str(ic_dir))
    except Exception as e:   # not a bigfile / unreadable dir
        raise ValueError(f"{ic_dir}: cannot open IC bigfile ({e!r})") from e
    with bf:                                     # close the handle (looping is the use case)
        try:
            attrs = bf["Header"].attrs
            keys = set(attrs.keys())
        except Exception as e:   # skeleton/mid-transfer IC: Header has no data
            raise ValueError(f"{ic_dir}: cannot read IC Header ({e!r}); skeleton/corrupt?") from e
        if "BoxSize" not in keys:
            raise ValueError(f"{ic_dir}: Header has no BoxSize")
        box_kpc_h = _attr(attrs, "BoxSize")
        hubble = _attr(attrs, "HubbleParam") if "HubbleParam" in keys else None
        omega0 = _attr(attrs, "Omega0") if "Omega0" in keys else None
        omega_lambda = _attr(attrs, "OmegaLambda") if "OmegaLambda" in keys else None
        time = _attr(attrs, "Time") if "Time" in keys else None
        if "Redshift" in keys:
            redshift = _attr(attrs, "Redshift")
        elif time is not None:
            redshift = units.scale_factor_to_redshift(time)
        else:
            redshift = float("nan")
            warnings.warn(f"{ic_dir}: Header has no Redshift/Time; redshift set to NaN")

        if field == "cic":
            block_name = f"{t}/Position"
            if block_name not in bf.blocks:
                raise ValueError(
                    f"{ic_dir}: no '{block_name}' block (ptype={ptype!r} absent in this IC)"
                )
            block = bf[block_name]
            npart = int(block.size)
            rho = np.zeros((nmesh, nmesh, nmesh), dtype=np.float64)
            for start in range(0, npart, chunk_size):
                stop = min(start + chunk_size, npart)
                pos = block[start:stop]              # (chunk, 3) comoving kpc/h
                mesh.cic_paint(pos, nmesh, boxsize=box_kpc_h, out=rho)
            delta = mesh.to_overdensity(rho).astype(np.float32)
        else:  # field == "icdensity": the native linear delta_1 on the Lagrangian grid
            for blk in (f"{t}/ICDensity", f"{t}/ID"):
                if blk not in bf.blocks:
                    raise ValueError(f"{ic_dir}: no '{blk}' block for field='icdensity'")
            delta, npart = _load_icdensity_grid(bf, t, nmesh, chunk_size)
    return ICField(
        delta=delta,
        nmesh=nmesh,
        box=units.kpc_h_to_mpc_h(box_kpc_h),
        ptype=ptype,
        redshift=redshift,
        npart=npart,
        space="real",
        meta={
            "ic_dir": str(ic_dir),
            "backend": backend,
            "field": field,                          # "cic" (Eulerian) | "icdensity" (linear delta_1)
            "cell_kpc_h": box_kpc_h / nmesh,
            "hubble": hubble,
            # cosmology so the consumer can compute the growth factor D(z) needed
            # to rescale this z_init field to the flux redshift (see docstring):
            "Omega0": omega0,
            "OmegaLambda": omega_lambda,
            "Time": time,
            "los_is_velocity_axis": False,           # real space (cf. tau)
        },
    )


def load_ic_velocity_mesh(
    ic_dir: StrPath,
    ptype: str = "dm",
    nmesh: int = 256,
    field: str = "velocity",
    chunk_size: int = 8_000_000,
) -> ICVelocityField:
    """CIC-paint the IC particle velocities onto an ``nmesh^3`` mesh.

    Streams ``Position`` + ``Velocity`` in chunks and accumulates, per component
    ``a``, the CIC momentum and the CIC counts::

        p_a(x) = sum_i v_{i,a} W(x - x_i)      n(x) = sum_i W(x - x_i)

    (Particles are equal-mass, so the mass factors out of ``p/n``.)

    Parameters
    ----------
    ic_dir, ptype, nmesh, chunk_size : as :func:`load_ic_density`.
    field : {"velocity", "momentum"}
        ``"velocity"`` (default): ``p / n`` — the mass-weighted mean velocity in
        each cell, in peculiar km/s. Cells with no particles are set to **0** and
        counted in ``meta["empty_cells"]`` (a warning is raised if any); at
        z ~ 99 with ``nmesh <= ngrid`` there should be none, so a nonzero count
        means your mesh is finer than the particle grid.
        ``"momentum"``: the raw ``p`` (mass-weighted, linear in ``v``) — the field
        to Fourier transform if you want a momentum/velocity-divergence spectrum
        without the ``p/n`` ratio's noise in low-density cells.

    Velocities are peculiar km/s: the IC Header's ``UsePeculiarVelocity`` flag is
    read and applied (see :func:`priya_loader.units.ic_velocity_to_peculiar_kms`).

    Memory: peak resident is ``~4x`` :func:`load_ic_density`'s peak at the same
    ``nmesh`` — ``mom`` is ``3*nmesh^3`` float64 (vs. density's one ``nmesh^3``
    grid), plus ``cnt`` (``nmesh^3`` float64) and one chunk's working set; the
    ``field="velocity"`` normalisation divides ``mom`` in place rather than
    allocating a second ``3*nmesh^3`` output. See the README's IC memory table
    for a worked example — it does **not** apply as-is to this function.

    Known inefficiency (deliberately deferred, not fixed here): each chunk calls
    :func:`priya_loader.mesh.cic_paint` 4 times (once for ``cnt``, once per
    velocity component for ``mom``), recomputing the same 8 CIC corner weights
    each time. Correct but ~4x more painting work than necessary; left alone
    because ``cic_paint`` itself is verified bit-for-bit and out of scope here.

    Returns
    -------
    ICVelocityField
        ``v`` has shape ``(3, nmesh, nmesh, nmesh)``, indexed ``[component][x,y,z]``
        on the same grid/origin as :class:`ICField` (so it co-registers with the
        density mesh and, via the HANDOFF recipe, with tau).
    """
    if ptype not in PTYPE:
        raise ValueError(f"ptype must be one of {sorted(PTYPE)}; got {ptype!r}")
    if field not in ("velocity", "momentum"):
        raise ValueError(f"field must be 'velocity' or 'momentum'; got {field!r}")
    if nmesh < 1 or chunk_size < 1:
        raise ValueError(f"nmesh and chunk_size must be >= 1 (got {nmesh}, {chunk_size})")
    try:
        import bigfile
    except ImportError as e:  # pragma: no cover
        raise ImportError("reading ICs needs bigfile: pip install priya_loader[ic]") from e

    t = PTYPE[ptype]
    try:
        bf = bigfile.File(str(ic_dir))
    except Exception as e:
        raise ValueError(f"{ic_dir}: cannot open IC bigfile ({e!r})") from e
    with bf:
        try:
            attrs = bf["Header"].attrs
            keys = set(attrs.keys())
        except Exception as e:
            raise ValueError(f"{ic_dir}: cannot read IC Header ({e!r}); skeleton/corrupt?") from e
        if "BoxSize" not in keys:
            raise ValueError(f"{ic_dir}: Header has no BoxSize")
        box_kpc_h = _attr(attrs, "BoxSize")
        hubble = _attr(attrs, "HubbleParam") if "HubbleParam" in keys else None
        omega0 = _attr(attrs, "Omega0") if "Omega0" in keys else None
        omega_lambda = _attr(attrs, "OmegaLambda") if "OmegaLambda" in keys else None
        time = _attr(attrs, "Time") if "Time" in keys else None
        if "Redshift" in keys:
            redshift = _attr(attrs, "Redshift")
        elif time is not None:
            redshift = units.scale_factor_to_redshift(time)
        else:
            redshift = float("nan")
            warnings.warn(f"{ic_dir}: Header has no Redshift/Time; redshift set to NaN")
        if time is None and np.isfinite(redshift):
            time = units.redshift_to_scale_factor(redshift)
        upv = int(_attr(attrs, "UsePeculiarVelocity")) if "UsePeculiarVelocity" in keys else None

        for blk in (f"{t}/Position", f"{t}/Velocity"):
            if blk not in bf.blocks:
                raise ValueError(f"{ic_dir}: no '{blk}' block (ptype={ptype!r})")
        pblk, vblk = bf[f"{t}/Position"], bf[f"{t}/Velocity"]
        npart = int(pblk.size)
        if int(vblk.size) != npart:
            raise ValueError(
                f"{ic_dir}: Position ({npart}) and Velocity ({vblk.size}) sizes differ"
            )

        mom = np.zeros((3, nmesh, nmesh, nmesh), dtype=np.float64)
        cnt = np.zeros((nmesh, nmesh, nmesh), dtype=np.float64)
        for start in range(0, npart, chunk_size):
            stop = min(start + chunk_size, npart)
            pos = pblk[start:stop]                                   # (chunk, 3) kpc/h
            vel = units.ic_velocity_to_peculiar_kms(vblk[start:stop], time, upv)
            mesh.cic_paint(pos, nmesh, boxsize=box_kpc_h, out=cnt)   # counts
            for a in range(3):
                mesh.cic_paint(pos, nmesh, boxsize=box_kpc_h, out=mom[a],
                               weights=vel[:, a])                    # momentum

    empty = int((cnt == 0).sum())
    if field == "velocity":
        safe = np.where(cnt > 0, cnt, 1.0)          # 0/0 -> 0, never NaN
        mom /= safe                                 # in-place: avoid a second 3*nmesh^3 f64 copy
        out = mom
        if empty:
            warnings.warn(
                f"{empty} of {nmesh ** 3} cells are empty (no particles) and were set "
                f"to v=0; nmesh={nmesh} is finer than the particle grid"
            )
    else:
        out = mom

    return ICVelocityField(
        v=out.astype(np.float32),
        nmesh=nmesh,
        box=units.kpc_h_to_mpc_h(box_kpc_h),
        ptype=ptype,
        redshift=redshift,
        field=field,
        npart=npart,
        units="km/s (peculiar)",
        space="real",
        meta={
            "ic_dir": str(ic_dir),
            "cell_kpc_h": box_kpc_h / nmesh,
            "empty_cells": empty,
            "use_peculiar_velocity": upv,
            "hubble": hubble,
            "Omega0": omega0,
            "OmegaLambda": omega_lambda,
            "Time": time,
            "los_is_velocity_axis": False,
        },
    )
