"""Initial-conditions density loader: MP-GenIC ``bigfile`` particles -> mesh.

Streams particle ``Position`` from the IC bigfile in chunks and paints them onto
a periodic ``nmesh^3`` mesh (cloud-in-cell, :mod:`priya_loader.mesh`), returning
the overdensity ``delta = rho/<rho> - 1``. The full particle load is never
resident: peak memory is ``~2 * nmesh^3`` float64 plus one chunk (see
:mod:`priya_loader.mesh`), so coarse meshes run on a NERSC login node
(recommended ``nmesh <= 512``). ``bigfile`` is an optional dependency
(``pip install priya_loader[ic]``).

What this field IS
------------------
* Two fields are available:
    - ``field="cic"`` (default): the **Eulerian density of the displaced
      particles** — CIC-paint of the LPT/Zel'dovich ``Position`` block.
    - ``field="icdensity"``: the **native linear density contrast delta_1** on the
      **Lagrangian** grid (the ``ICDensity`` block reshaped by ``ID``). This is the
      linear field a field-level bias estimator (de Belsunce et al.) wants. It is
      Lagrangian-indexed delta_1(q), which equals the Eulerian linear field at
      first order (valid for linear bias; the z=99 displacements are tiny).
      Caveats: it carries GenIC's ~1-cell Gaussian k-smoothing (sub-percent at
      k<~1 h/Mpc); it is window-free only at ``nmesh == ngrid`` — for
      ``nmesh < ngrid`` the block-average imposes a real-space top-hat (a *sinc*
      window, NOT the CIC ``sinc^2``) that does not cancel in b_F, so deconvolve
      for finite-k (it -> 1 at the low-k modes that drive the leading bias). gas
      vs dm here selects the species' own CLASS transfer (gas=baryon, dm=CDM).
      Prefer ``"icdensity"`` for the bias cross-spectrum; ``"cic"`` for the
      Eulerian/evolved density.
* **At the IC redshift** ``z_init ~ 99`` — the returned amplitude is the z=99
  one. For a bias cross-spectrum at the flux redshift, the consumer must rescale
  by the linear growth factor ``D(z_flux) / D(z_init)`` (a scale-independent
  scalar; e.g. ~26x at z=2.8). We expose ``Omega0/OmegaLambda/Time`` in ``meta``
  so ``D(z)`` is computable; the rescale itself is left to the consumer.
  (At z=99 the displacements are tiny, so this field ~ the linear field.)
* **Real space** (``space="real"``; cf. ``TauGrid.space == "redshift"``).
  Crossing this real-space delta with the redshift-space flux is the *intended*
  Kaiser estimator (gives the full mu-shape for b_F and beta_F) — do not add RSD.
* **Raw, uncompensated CIC** (``field="cic"`` only) — carries the CIC ``sinc^2``
  window; deconvolve for an unbiased finite-k cross-spectrum (see
  :mod:`priya_loader.mesh`). (The ``"icdensity"`` route's window is a *sinc*
  top-hat, not ``sinc^2`` — see above.)
* **``ptype="dm"`` is a total-matter proxy** — exact at ``k -> 0``; baryons
  differ at the percent level on quasilinear scales at z=99.

Co-registration with a tau cube (read this before cross-correlating)
--------------------------------------------------------------------
``ICField.delta`` is indexed ``[x, y, z]`` (``axes = ("x", "y", "z")``), origin 0,
cell ``box/nmesh`` — the same grid origin as the fake_spectra ``cofm``. The tau
cube from :func:`priya_loader.load_tau_grid` is **anisotropic**:
``(ngrid, ngrid, nbins)`` with ``nbins != ngrid``, its first two axes transverse
(``box/ngrid``) and its **last axis a redshift-space velocity axis**
(``dv_kms ~ 10`` km/s), ordered per ``TauGrid.cube_axes`` (e.g. axis=1 -> y,z,x).
So:
  * match the **transverse** plane by painting at ``nmesh = tau.ngrid`` (=480)
    and transposing the IC mesh to ``cube_axes``;
  * the **LOS** axis is NOT a common ``nmesh`` — resample tau's velocity LOS onto
    a common comoving grid (using ``tau.meta["dv_kms"]`` / ``units.velfac``), or
    use a transverse/projected cross-statistic.
The loader only meshes the IC; it never transforms tau.

Provenance (see PROVENANCE.md)
-----------------------------
* ``Position`` = Lagrangian grid ``q`` + 1LPT Zel'dovich displacement ``Psi``
  (``libgenic/zeldovich.c:243-244`` ``Pos += Disp``; written ``save.c:73``;
  MP-Gadget @ 471711f8). First order only — no 2LPT.
* The native ``ICDensity`` block (which we do NOT read) is the **linear density
  contrast delta_1** on the Lagrangian grid (= white noise x ``DeltaSpec(k)``,
  ``zeldovich.c:182,284`` / ``power.c:52-65``; saved ``save.c:72``), with a
  ~1-cell Gaussian smoothing. That is the exact ``delta_1`` a field-level bias
  estimator wants; the CIC-of-``Position`` field here equals it to O(delta^2) at
  z=99 but carries the CIC window. The native linear field is available via
  ``field="icdensity"`` (exact at ``nmesh==ngrid``; a sinc top-hat below that).
* The IC linear power spectrum / transfer functions are generated by **CLASS**
  (via the ``classy``/``classylss`` Python binding), NOT CAMB, in
  ``SimulationRunner/simulationics.py::cambfile()`` (@ 5adf4fe); the
  ``camb_linear/`` dir name and ``camb_git`` field are legacy CAMB labels
  (``camb_git`` = the classylss version).

Units: ``Position`` is comoving kpc/h; ``box`` is reported in Mpc/h.
"""
from __future__ import annotations

import os
import warnings
from dataclasses import dataclass, field
from typing import Any, Dict, Union

import numpy as np

from . import mesh, units

StrPath = Union[str, os.PathLike]

#: particle-type name -> bigfile block prefix (MP-Gadget convention: 0 gas, 1 DM)
PTYPE = {"gas": 0, "dm": 1}


@dataclass
class ICField:
    """Initial-condition overdensity on a mesh."""

    delta: np.ndarray            # (nmesh, nmesh, nmesh) float32 overdensity
    nmesh: int
    box: float                   # Mpc/h
    ptype: str                   # "gas" | "dm"
    redshift: float              # IC redshift (z_init, ~99); see growth note below
    npart: int                   # particles painted
    axes: tuple = ("x", "y", "z")
    space: str = "real"          # real space (cf. TauGrid.space == "redshift")
    meta: Dict[str, Any] = field(default_factory=dict, repr=False)


def _icbrt(n: int) -> int:
    """Exact integer cube root of ``n``, or raise (n is not a perfect cube)."""
    g = int(round(n ** (1.0 / 3.0)))
    for c in (g - 1, g, g + 1):
        if c > 0 and c ** 3 == n:
            return c
    raise ValueError(f"ICDensity route: {n} particles is not a perfect cube (ngrid^3)")


def _load_icdensity_grid(bf, t, nmesh, chunk_size):
    """Return (delta_1, npart): the native linear ``ICDensity`` field on the
    Lagrangian grid, block-averaged to ``nmesh^3``, plus the particle count.

    ``ICDensity`` is the linear density contrast at each particle's Lagrangian
    grid site. The row-major site is ``(ID - 1) mod ngrid^3`` (the per-type
    ``FirstID`` is a multiple of ``ngrid^3``), so no ID sort/min pass is needed.
    Streamed in chunks (memory-safe): resident RAM is ~3*nmesh^3 float64
    (``ssum`` + ``cnt`` + one transient bincount) + one chunk.

    Exact only at ``nmesh == ngrid``; for ``nmesh < ngrid`` the block-average is
    a real-space top-hat (a ``sinc`` window on delta_1(k)) — fine at low k,
    deconvolve for finite-k cross-spectra. ``nmesh`` should divide ``ngrid``.
    """
    idblk = bf[f"{t}/ID"]
    dblk = bf[f"{t}/ICDensity"]
    npart = int(idblk.size)
    if npart == 0:
        raise ValueError("ICDensity route: empty ID block")
    if int(dblk.size) != npart:
        raise ValueError(f"ICDensity route: ID ({npart}) and ICDensity ({dblk.size}) sizes differ")
    ngrid = _icbrt(npart)
    if nmesh > ngrid:
        raise ValueError(
            f"ICDensity route: nmesh={nmesh} > ngrid={ngrid} (cannot upsample a block-average)"
        )
    if ngrid % nmesh != 0:
        warnings.warn(
            f"ICDensity downsample is uneven: nmesh={nmesh} does not divide ngrid={ngrid}"
        )

    n3 = nmesh * nmesh * nmesh
    ssum = np.zeros(n3, dtype=np.float64)
    cnt = np.zeros(n3, dtype=np.float64)
    ng2 = ngrid * ngrid
    gmin = gmax = None
    for s in range(0, npart, chunk_size):
        stop = min(s + chunk_size, npart)
        ids = idblk[s:stop].astype(np.int64)
        lo, hi = int(ids.min()), int(ids.max())
        gmin = lo if gmin is None else min(gmin, lo)
        gmax = hi if gmax is None else max(gmax, hi)
        lag = (ids - 1) % npart                              # within-type row-major index
        i = (lag // ng2) * nmesh // ngrid
        j = ((lag // ngrid) % ngrid) * nmesh // ngrid
        k = (lag % ngrid) * nmesh // ngrid
        flat = (i * nmesh + j) * nmesh + k
        ssum += np.bincount(flat, weights=dblk[s:stop].astype(np.float64), minlength=n3)
        cnt += np.bincount(flat, minlength=n3)
    # Completeness: a full type block has contiguous IDs, so range == count.
    if gmax - gmin + 1 != npart:
        raise ValueError(
            f"ICDensity route: IDs are not a complete contiguous block "
            f"(range {gmax - gmin + 1} != count {npart}); partial/corrupt IC?"
        )
    cnt[cnt == 0] = 1.0
    return (ssum / cnt).reshape(nmesh, nmesh, nmesh).astype(np.float32), npart


def _attr(attrs, key):
    """Read a scalar bigfile Header attr as a python float.

    bigfile stores attrs as arrays, so scalars come back as 1-element arrays.
    Only call this on scalar attrs — ``ravel()[0]`` would silently take the first
    element of a vector attr (e.g. ``MassTable``).
    """
    return float(np.asarray(attrs[key]).ravel()[0])


def load_ic_density(
    ic_dir: StrPath,
    ptype: str = "dm",
    nmesh: int = 256,
    chunk_size: int = 8_000_000,
    backend: str = "numpy",
    field: str = "cic",
) -> ICField:
    """Load the IC density field for one particle type as an ``nmesh^3`` overdensity.

    Parameters
    ----------
    ic_dir : str or os.PathLike
        An MP-GenIC IC bigfile directory (contains ``Header`` and ``<t>/Position``).
    ptype : {"dm", "gas"}
        Particle type (1=DM, 0=gas).
    nmesh : int
        Mesh cells per side (coarse default; raise for finer fields).
    chunk_size : int
        Particles read per streaming chunk (memory vs. overhead tradeoff).
    backend : {"numpy"}
        Painter backend. Only the lightweight numpy CIC is implemented; an
        ``nbodykit`` backend may be added later.
    field : {"cic", "icdensity"}
        ``"cic"`` (default): CIC overdensity of the displaced ``Position`` block.
        ``"icdensity"``: the native linear ``delta_1`` (``ICDensity`` block
        reshaped by ``ID`` to the Lagrangian grid, block-averaged to ``nmesh``) —
        the exact linear field for the bias cross-spectrum.

    Returns
    -------
    ICField
        For ``field="icdensity"`` ``delta`` is the Lagrangian linear ``delta_1``
        (not mean-subtracted; ``nmesh`` should divide ``ngrid``, ``nmesh<=ngrid``);
        for ``"cic"`` it is the Eulerian overdensity ``rho/<rho>-1``.
    """
    if ptype not in PTYPE:
        raise ValueError(f"ptype must be one of {sorted(PTYPE)}; got {ptype!r}")
    if backend != "numpy":
        raise ValueError(f"unknown backend {backend!r} (only 'numpy' is implemented)")
    if field not in ("cic", "icdensity"):
        raise ValueError(f"field must be 'cic' or 'icdensity'; got {field!r}")
    if nmesh < 1 or chunk_size < 1:
        raise ValueError(f"nmesh and chunk_size must be >= 1 (got {nmesh}, {chunk_size})")
    try:
        import bigfile
    except ImportError as e:  # pragma: no cover
        raise ImportError("reading ICs needs bigfile: pip install priya_loader[ic]") from e

    t = PTYPE[ptype]
    with bigfile.File(str(ic_dir)) as bf:        # close the handle (looping is the use case)
        attrs = bf["Header"].attrs
        keys = set(attrs.keys())
        if "BoxSize" not in keys:
            raise ValueError(f"{ic_dir}: Header has no BoxSize")
        box_kpc_h = _attr(attrs, "BoxSize")
        hubble = _attr(attrs, "HubbleParam") if "HubbleParam" in keys else None
        omega0 = _attr(attrs, "Omega0") if "Omega0" in keys else None
        omega_lambda = _attr(attrs, "OmegaLambda") if "OmegaLambda" in keys else None
        time = _attr(attrs, "Time") if "Time" in keys else None
        if "Redshift" in keys:
            redshift = _attr(attrs, "Redshift")
        elif time is not None:
            redshift = units.scale_factor_to_redshift(time)
        else:
            redshift = float("nan")
            warnings.warn(f"{ic_dir}: Header has no Redshift/Time; redshift set to NaN")

        if field == "cic":
            block_name = f"{t}/Position"
            if block_name not in bf.blocks:
                raise ValueError(
                    f"{ic_dir}: no '{block_name}' block (ptype={ptype!r} absent in this IC)"
                )
            block = bf[block_name]
            npart = int(block.size)
            rho = np.zeros((nmesh, nmesh, nmesh), dtype=np.float64)
            for start in range(0, npart, chunk_size):
                stop = min(start + chunk_size, npart)
                pos = block[start:stop]              # (chunk, 3) comoving kpc/h
                mesh.cic_paint(pos, nmesh, boxsize=box_kpc_h, out=rho)
            delta = mesh.to_overdensity(rho).astype(np.float32)
        else:  # field == "icdensity": the native linear delta_1 on the Lagrangian grid
            for blk in (f"{t}/ICDensity", f"{t}/ID"):
                if blk not in bf.blocks:
                    raise ValueError(f"{ic_dir}: no '{blk}' block for field='icdensity'")
            delta, npart = _load_icdensity_grid(bf, t, nmesh, chunk_size)
    return ICField(
        delta=delta,
        nmesh=nmesh,
        box=units.kpc_h_to_mpc_h(box_kpc_h),
        ptype=ptype,
        redshift=redshift,
        npart=npart,
        space="real",
        meta={
            "ic_dir": str(ic_dir),
            "backend": backend,
            "field": field,                          # "cic" (Eulerian) | "icdensity" (linear delta_1)
            "cell_kpc_h": box_kpc_h / nmesh,
            "hubble": hubble,
            # cosmology so the consumer can compute the growth factor D(z) needed
            # to rescale this z_init field to the flux redshift (see docstring):
            "Omega0": omega0,
            "OmegaLambda": omega_lambda,
            "Time": time,
            "los_is_velocity_axis": False,           # real space (cf. tau)
        },
    )
